import numpy as np
import matplotlib.pyplot as plt

def logistic_map(r, x):
    """Calculate the next value in the logistic map."""
    return r * x * (1 - x)

def generate_chaos_sequence(r, x0, n):
    """Generate a chaos sequence using the logistic map."""
    sequence = []
    x = x0
    for _ in range(n):
        x = logistic_map(r, x)
        sequence.append(x)
    return sequence

def save_chaos_sequence(sequence, filename):
    """Save the chaos sequence to a file."""
    np.savetxt(filename, sequence, delimiter=',')
    print(f"Chaos sequence saved to {filename}")

def plot_chaos_sequence(sequence):
    """Plot the chaos sequence."""
    plt.figure(figsize=(10, 5))
    plt.plot(sequence, marker='o', linestyle='-', markersize=3)
    plt.title("Chaos Sequence Generated by Logistic Map")
    plt.xlabel("Iteration")
    plt.ylabel("Value")
    plt.grid()
    plt.show()

if __name__ == "__main__":
    # Parameters for chaos generation
    r = 3.9  # Parameter for chaos (should be in the range (3.57, 4) for chaos)
    x0 = 0.5  # Initial condition
    n = 100  # Number of iterations

    # Generate the chaos sequence
    chaos_sequence = generate_chaos_sequence(r, x0, n)

    # Save the chaos sequence to a file
    save_chaos_sequence(chaos_sequence, "chaos_sequence.csv")

    # Plot the chaos sequence
    plot_chaos_sequence(chaos_sequence)
